---

- name: Add ACL List item 
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  tasks:
  - name: load new acl into device
    ios_config:
      lines:
      - 10 permit ip host 192.0.2.1 any log
    parents: ip access-list extended test
    before: no ip access-list extended test
    match: exact
    
