---

- name: Add ACL List item 
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  tasks:
  - name: load new acl into device
    ios_config:
      lines:
      - 20 permit ip host 192.0.2.1 any log
      parents: ip access-list 10
#      before: no ip access-list 10
      match: exact
    
