
- name: Add ACL List item 
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  tasks:
  - name: Create an access-list
    ios_config:
      lines: access-list 10 permit 10.1.10.207
      lines: ip access-list resequence 10 10 10
