
- name: Add ACL List item 
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  tasks:
  - name: Create an access-list
    ios_config:
      lines: access-list 166 permit tcp any any eq 99   
