---

- name: Add User
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  
  tasks:   
  - name: Merge provided configuration with device configuration
    ios_vlans:
      config:
      - name: Vlan_3
        vlan_id: 3
        state: active
        shutdown: disabled
        remote_span: 10
      state: merged
