---

- name: Merge ACL
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  
  tasks:   
  - name: Merge provided configuration with device configuration
    aces:
      config:
      - name: 110
        aces:
      - sequence: 10
        protocol_options:
          icmp:
            traceroute: true
      - grant: deny
        protocol_options:
          tcp:
            ack: true
        source:
          host: 198.51.100.0
        destination:
          host: 198.51.110.0
          port_protocol:
            eq: telnet
