---

- name: Add VLAN 
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  
  tasks:   
  - name: Add VLAN configuration to switch 
    ios_vlans:
      config:
      - name: "{{ vlan_name }}"
        vlan_id: 5
        state: active
        shutdown: disabled
      state: merged
