---
- name: Mod ACL 
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli

- name: Merge module attributes of given access-groups
  cisco.ios.ios_acl_interfaces:
    config:
    - name: GigabitEthernet0/2
      access_groups:
      - afi: ipv4
        acls:
        - name: 156
          direction: in
   state: merged
