---

- name: Add User
  hosts: all
  ansible_become: yes
  ansible_become_method: enable
  auth_pass: ansible
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
#  authorize: yes 
#  auth_pass: "{{ auth_pass }}"

  tasks:   
    - name: create a new user
      ios_user:
        name: "{{ new_user }}"
        configured_password: '{{ new_password }}'
        password_type: password
#    nopassword: true
#    sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
    
    
