---
- name: convert configured ACLs to structured data
  hosts: all
  gather_facts: false
  tasks:


    - name: Use the ACLs resource module to gather the current config
       ios_acls:
           state: gathered
           register: acls

    - name: Create inventory directory
      file:
       path: "{{ inventory_dir }}/{{ inventory_hostname }}"
       state: directory

    - name: Write the ACL configuration to a file
      copy:
        content: "{{ {‘acls’: acls['gathered']} | to_nice_yaml }}"
        dest: "{{ inventory_dir }}/{{ inventory_hostname }}/acls.yaml"
