---

- name: Add VLAN 
  hosts: all
  become: yes
  become_method: enable
  collections:
    - cisco.ios
  gather_facts: false
  connection: network_cli
  
  tasks:   
  - name: Add VLAN configuration to switch 
    ios_acl_interfaces:
      config:
   - name: GigabitEthernet0/2
     access_groups:
     - afi: ipv4
       acls:
       - name: 156
         direction: in
    state: merged
