---
- name: UPDATE VLAN / GATHER FACTS FOR IOS
  hosts: all
  gather_facts: true
  connection: network_cli
  tasks:
    - name: Run cli_command on Cisco IOS and display results
      block:
    - name: Run cli_command on Cisco IOS
        cisco.ios.ios_command:
          command:
          - show version
          - show interfaces
        register: result

    - name: Display result to terminal window
      debug:
        var: result.stdout_lines
      when: ansible_network_os == 'cisco.ios.ios'
