---
- name: Create a new group
  hosts: all
  collections:
    - ansible.windows
  tasks:
  - name: Ensure user bob is present with address information
    win_domain_user:
      name: bob
      firstname: Todd
      surname: Smith
      company: ToddCo
      password: nopassword
      state: present
      groups:
       - Ansible Users
      street: 123 4th St.
      city: Sometown
      state_province: IN
      postal_code: 12345
      country: US
      attributes:
      telephoneNumber: 555-123456
