---
- name: Create a new group
  hosts: all
  collections:
    - ansible.windows
  tasks:
  - name: Create group with delete protection enabled and custom attributes
    win_domain_group:
      name: "{{ group_name }}"
      scope: domainlocal
      category: security
      attributes:
       mail: helpdesk@ansible.com
       wWWHomePage: www.ansible.com
       ignore_protection: yes
