---
- name: Create a new group
  hosts: all
  collections:
    - ansible.windows
  tasks:
  - name: "Ensure user {{ user_name }} to group {{ group_name }}"  
    win_domain_user:
      name: "{{ user_name }}"
      firstname: Todd
      surname: Smith
      company: ToddCo
      password: "{{ user_password }}"
      state: present
      groups:
       - "{{ group_name }}"
      street: 123 4th St.
      city: Sometown
      state_province: IN
      postal_code: 12345
      country: US
      attributes:
      telephoneNumber: 555-123456
