---
- name: this is hello world
  hosts: all
  tasks:
    - name: Hello World
      debug:
        msg: "Hello World" 
      environment:
        http_proxy: http://proxy.example.com:8080
        https_proxy: https://proxy.example.com:443
