---
- name: Apache server installed
  hosts: 10.1.10.84
  become: yes
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd-2.2.29-1.4.amzn1
      state: present
  - name: copy index.html
    template:
      src: index.html
      dest: /var/www/html
  - name: stop Apache server
    service:
      name: httpd
      state: stopped
  - name: Update Apache
    yum:
      name: update , httpd
