---
- name: Apache server installed
  hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  - name: copy index.html
    template:
      src: index.html
      dest: /var/www/html
  - name: start Apache server
    service:
      name: httpd
      state: started
