--- #  Sample Ansible Play for Javier

- name: Server Log Files Cleanup
  hosts: all
  gather_facts: no
  become: yes

  tasks:

   - name: Look for Files

     find:

       paths: "{{ item }}"

  #     age: 90d

       patterns: 'todd*,amir*,junk*'

     with_items:

       - /home/
       - /home/todd/
       - /home/amir/

     register: oldlogfiles
    
 
   - debug:
       msg: " {{ oldlogfiles.results }}"
       
   - set_fact: 

   #    newlistoffiles={{ oldlogfiles.results | map(attribute="path") | list }}

  

   - debug:

   #    msg: "{{ newlistoffiles.path }}"

 

#   - name: Delete files 

#     file:

#       path: "{{ item }}"

#       state: absent

#     with_items: '{{ path }}' 
