---
- name: install mysql on db servers
  hosts: db
  tasks:
    - name: download epel-release
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        state: present 
    - name: install mysql
      yum:
        name: "mysql-server"
        state: present
    - name: enable mysql
      service:
        name: mysqld
        state: restarted
        enabled: yes
        
- name: install http and ftp
  hosts: web
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: Install Website Code
      template:
        src: index.html
        dest: /var/www/html
    - name: copy index2.html
      template:
        src: index2.html
        dest: /var/www/html    
    - name: install ftpd
      yum:
        name: vsftpd
        state: latest
    - name: enable httpd service
      service:
        name: httpd
        state: started
        enabled: true
    - name: enabled ftpd service
      service:
        name: vsftpd
        state: started
        enabled: true
    - name: enable Firewalld service
      service:
        name: firewalld
        state: started
        enabled: true
    - name: add httpd to firewalld
      firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
    - name: add ftp to firewalld
      firewalld:
        service: ftp
        state: enabled
        permanent: true     
        immediate: true
