---
- name: Remove EPEL Repository
  hosts: all
  become: yes
  tasks:
    - name: Remove repository (and clean up left-over metadata)
      yum_repository:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: absent
     # notify: yum-clean-metadata
