---
- name: Remove EPEL Repository
  hosts: all
  become: yes
  tasks:
    - name: Remove repository (and clean up left-over metadata)
      yum_repository:
        name: Red Hat Enterprise Linux 7 Server - Extras (RPMs)
        state: absent
     # notify: yum-clean-metadata
