---
- name: Play to create a user
  hosts: all
  gatner_facts: no
  tasks:
    - name: create a user 
      user:
        name: "{{ user_name }}"
        shell: /bin/bash
        state: absent
        
