---
- name: Red Hat Enterprise Linux Compliance Scan
  hosts: all
  vars:
    scap_dir: /var/www/html/security-scan
  become: yes
  gather_facts: yes
  tasks:
  - name: yum install openscap-scanner
    yum:
      name: openscap-scanner
      state: latest
  - name: yum install scap-security-guide
    yum:
      name: scap-security-guide
      state: latest
  - name: Removing {{ scap_dir }}
    file:
      path: "{{ scap_dir }}"
      state: absent
  - name: Creating {{ scap_dir }}
    file:
      path: "{{ scap_dir }}"
      state: directory
      owner: root
      group: root
      mode: 0755
  - name: Running Red Hat Compliance Scan
    command: "oscap xccdf eval --profile xccdf_org.ssgproject.content_profile_ospp --report /var/www/html/security-scan/report.html /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
    ignore_errors: yes
    register: oscap_result
  - debug:
      var: oscap_result.stdout_lines
