---
- name: Close Service Catalog Item Request
  hosts: all
  connection: local
  gather_facts: true

  tasks:

  - name: open servicenow request
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: sc_request
      number: "{{ snow_request }}"
      data:
        work_notes: "Ansible Automation - Changed {{ member_name }} to state {{ member_state }} on F5 device {{ private_ip }}"
        state: 3
    delegate_to: localhost
    become: false

  - name: close servicenow request item
    snow_record:
      username: "{{ snow_user }}"
      password: "{{ snow_password }}"
      instance: "{{ snow_instance }}"
      state: present
      table: sc_req_item
      number: "RITM{{ snow_request.split('REQ')[1] }}"
      data:
        work_notes: "Ansible Automation - Changed {{ member_name }} to state {{ member_state }} on F5 device {{ private_ip }}"
        state: 3
    delegate_to: localhost
    become: false
