- hosts: localhost
  pre_tasks:
    - shell: ansible-galaxy install geerlingguy.docker
    - shell: ansible-galaxy install geerlingguy.pip
- hosts: all
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
