- hosts: all
  pre_tasks:
    command: ansible-galaxy install geerlingguy.docker
    command: ansible-galaxy install geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
