---
- name: Create a new group
  hosts: all
  tasks:
  - name: Windows - Listing local printers
    win_shell: 'wmic printer list brief'
    register: local_printer_list
  - debug:
        msg: "{{ local_printer_list }}"
        
