---
- name: check if a service is installed
  hosts: all
  tasks:
    - name: This is a server info pull
      win_service:
        name: dhcp
      register: service_info
    - debug:
        msg: "{{ service_info.stdout }}"
      
