---
- name: Create a new group
  hosts: all
  collections:
    - ansible.windows
  tasks:
  - name: Create Group Maybe
    ansible.windows.win_group:
      name: deploy
      description: Deploy Group
      state: present
    
